### ISSUE TITLE
Why does this package has a minimal node engine version

### ISSUE THREAD

**Issue by TheNoim** [markcellus/scroll-js#417]
https://github.com/markcellus/scroll-js/blob/master/package.json#L30

This is a client package, and it doesn't make any sense for this line to exist. If this was meant for development usage, then please move to something like `.nvmrc`. The engine field blocks the installation of the package in projects with node versions older than v16 for no reason.

**Comment by markcellus** [comment]
Because many consumers of this library generally bundle it with their apps. So the node version used by their bundler needs to be one that this package expects or they can run into errors during the bundling step. The `engines` here field enforces that.  So just because the library may work with your older version of node, doesn't mean it will work for everyone else.

`.nvmrc` only works if contributors have nvm installed on their machine, and the file is only used if the contributor knows to run `nvm use`. Because the `.nvmrc` file is not enforced, it doesn't stop someone from using the wrong node version and trying to check in a inconsistent package-lock.json file (node 16 and up refactors the lock file from earlier versions of node).

It's possible for me to remove that `engine` field if its causing issues for you on earlier versions of node, but I can't promise that no code introduced in the future will be compatible with your earlier version of node.

**Comment by TheNoim** [comment]
But this is still a frontend tool. The node version is completely irrelevant. The only thing which is relevant is the bundler you are using and this is completely independent from the node version. It doesn’t make any sense to enforce a node version.

**Comment by markcellus** [comment]
The node version of the bundler being used is not completely independent from the node version compatible to bundle this package. The bundler will pull in all code from this package from the entrypoint it makes available to the bundler. If the code released from this package is incompatible with that, it will be an issue.

As an alternative, you can use earlier versions of this package like [3.4.x](https://github.com/markcellus/scroll-js/releases/tag/v3.4.2) versions that can be installed with node versions as early as 14. But there's no intention to support node versions earlier than that. Either that, or feel free to fork the package and remove the engines field.

**Comment by dunklesToast** [comment]
Your library is not dependant to any Node.js version - it may be dependant to a specific bundler version like WebPack 4 or WebPack 5 (although it shouldn't and is not) or maybe a specific browser version because you use APIs that are not available for in some browsers. However, the `engine` field is not needed for this libraries end-users.

**Comment by TheNoim** [comment]
Why should a client package enforce the node version for your bundler?? That just non of a client packages business. It doesn’t matter on which node version the bundler is working, because it will not evaluate the code of the package itself!

**Comment by markcellus** [comment]
I've already given you a workaround for your older node versions. The engines field should not block your installation. Unless you're using `engines-strict` or using a very old node version it will raise as warning, not an error. 

If you feel very stongly about this, which appears to be the case, feel free to fork project and use that.
